### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by dweremeichik** [Abdera7mane/Discord-RPC-GDScript#1]
Hi :wave:,
this addon is missing a license which technically means others aren't allow to use/modify it. This effects the license validity of other plugins that may make use of this plugin such as: https://github.com/3ddelano/godot-editor-discord-presence/issues/5

**Comment by Abdera7mane** [comment]
My bad I thought I already did, thank you for pointing that out

**Comment by Abdera7mane** [comment]
The project is now licensed under the MIT license
