### ISSUE TITLE
 The identifier "StreamPeerUnix" isn't a valid type

### ISSUE THREAD

**Issue by amr-engineer** [Abdera7mane/Discord-RPC-GDScript#2]
## I think something is missing...

`res://addons/Discord RPC/ipc/pipe/UnixPipe.gd:(3,12)` + `res://addons/Discord RPC/ipc/pipe/UnixPipe.gd:(6,13)`
https://github.com/Abdera7mane/Discord-RPC-GDScript/blob/ba5db0ca46ec8292ea22ab60455ec037ef74322b/addons/Discord%20RPC/ipc/pipe/UnixPipe.gd#L3-L6

![image](https://user-images.githubusercontent.com/67455370/153776204-0ea937a4-b54e-46bd-9aff-e4d8a82463f8.png)

**Comment by Abdera7mane** [comment]
Was there any errors regarding loading `addons/godot-unix-socket/unix-socket.gdns` resource ?

**Comment by amr-engineer** [comment]
Sorry my bad, I forgot to add [Godot-UnixSocket](https://github.com/Abdera7mane/Godot-UnixSocket/) to the project
