### ISSUE TITLE
[Feature] Upload to Godot AssetLib 

### ISSUE THREAD

**Issue by 3ddelano** [Abdera7mane/Discord-RPC-GDScript#6]
It would be nice to have this plugin listed in Godot AssetLib as currently there are no proper plugins for Discord RPC for Godot 3 in the AssetLib.

**Comment by Abdera7mane** [comment]
Submitted the asset for 3.x, waiting for approval

**Comment by Abdera7mane** [comment]
https://godotengine.org/asset-library/asset/1950

**Comment by 3ddelano** [comment]
Nice!
