### ISSUE TITLE
Error with Payload in v.2.0.0

### ISSUE THREAD

**Issue by eldiabIo123** [Abdera7mane/Discord-RPC-GDScript#8]
![image](https://github.com/Abdera7mane/discord-rpc-gdscript/assets/64546079/54cc8315-6b38-4447-803f-78c9c86f11e1)

In Godot 4.2.1

`const Payload := DiscordRPCConnection.Payload #Line 656`

Error:
```
Linia 656:Error while getting cache for script "res://discord-rpc/DiscordRPCConnection.gd".
Linia 656:Assigned value for constant "Payload" isn't a constant expression.
Linia 706:Class "UpdateRichPresencePayload" hides a global script class.
```

![image](https://github.com/Abdera7mane/discord-rpc-gdscript/assets/64546079/1c6ec094-8c04-402d-9266-20a2c8a4c621)

**Comment by Abdera7mane** [comment]
Should be fixed now. Also you have to update `unix-socket` to `v2.0.1` if you care about supporting Linux or MacOS on Godot 4.2, and you do not need a `lib.gdextension` file inside, this plugin does lazy loading to prevent errors from loading dependencies on unsupported platforms

**Comment by Abdera7mane** [comment]
An other note: the file structure in `res://addons/unix-socket/` should look like this:
```
res://addons/unix-socket/
│
│_ libunixsocket.linux.debug.x86_64.so
│_ libunixsocket.linux.release.x86_64.so
│_ libunixsocket.macos.debug.universal.dylib
│_ libunixsocket.macos.release.universal.dylib
```

**Comment by eldiabIo123** [comment]
Okay, I update a unix-socket to v.2.0.1 and now i have a one error instead three 

![image](https://github.com/Abdera7mane/discord-rpc-gdscript/assets/64546079/8cd713ff-8c10-450f-9835-bc10a34ed30e)

**Comment by eldiabIo123** [comment]
missclick

**Comment by Abdera7mane** [comment]
you still had to update this project too, clone the master branch

**Comment by eldiabIo123** [comment]
![image](https://github.com/Abdera7mane/discord-rpc-gdscript/assets/64546079/4bb7d0cf-1917-4d82-a27f-7cd7efe94e47)

I download and reload project from master channel and still have a error

**Comment by Abdera7mane** [comment]
I was not able to replicate the issue. Try to delete `.godot/global_script_class_cache.cfg` then reload the project

**Comment by eldiabIo123** [comment]
I delete all files in AppData for godot and still is error on line 704

My project:
[Project.zip](https://github.com/Abdera7mane/discord-rpc-gdscript/files/14315420/Project.zip)

ps. I forgot to add script to control

**Comment by Abdera7mane** [comment]
I'm not getting any error on that line on the project aside from not deleting `res://addons/unix-socket/lib.gdextension` like I suggested. Anyway, `.godot/global_script_class_cache.cfg` is not located in AppData, `.godot` is a hidden folder in your project directory.

**Comment by eldiabIo123** [comment]
Sorry, I'm just a beginner in Godot and I already deleted that file and now the error is on line 656a and I know that the second error (the one below) is from something else.

[Still error.zip](https://github.com/Abdera7mane/discord-rpc-gdscript/files/14316728/Still.error.zip)
Godot may not be for me. I'm just going to give up. I don't want to waste your time anymore. I'll close this issue tomorrow.

Thanks for trying to help me.

**Comment by eldiabIo123** [comment]
![image](https://github.com/Abdera7mane/discord-rpc-gdscript/assets/64546079/2339f010-c9a4-42f3-8653-c5a8e3f2c46f)
Sorry, I'm just a beginner in Godot and I already deleted that file `.godot/cache`.

[Still error.zip](https://github.com/Abdera7mane/discord-rpc-gdscript/files/14316747/Still.error.zip)
Godot may not be for me. I'm just going to give up. I don't want to waste your time anymore. I'll close this issue tomorrow.

Thanks for trying to help me.
